export const styleSheet = {
    container:{
        width:'100vw',
        height:'100vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#D9D9D9',
    },
    loginContainer:{
        width:'40vw',
        height:'80vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#C5B5B5',
    },
    loginHeader:{
        width:'40vw',
        height:'20vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
       
    },
    loginFields:{
        width:'40vw',
        height:'30vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    loginButton:{
        width:'40vw',
        height:'10vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        
    },
    loginClickHere:{
        width:'40vw',
        height:'20vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',  
    }
}