export const styleSheet ={
    container:{
        width:'100vw',
        height:'100vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#D9D9D9',
    },
    header:{
        width:'100vw',
        height:'10vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'left',
        //border:'1px solid red',
    },
    bodyContainer:{
        width:'100vw',
        height:'90vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        //border:'1px solid red',
    },
    fieldContainer:{
        width:'80vw',
        height:'80vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        //border:'1px solid red',
    },
    fieldFields:{
        width:'40vw',
        height:'80vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        border:'1px solid red',
    }
}